In [ ]:
! pip install tensorflow

In [4]:
import tensorflow as tf

In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
sent = [
    'the ball of the century',
    'greatest of all time',
    'head of the table',
    'the peoples champ',
    'rest in peace'
]

In [7]:
sent

['the ball of the century',
 'greatest of all time',
 'head of the table',
 'the peoples champ',
 'rest in peace']

In [8]:
voc_size = 10000

In [9]:
one = [one_hot(words, voc_size) for words in sent]
print(one)

[[2172, 1215, 8323, 2172, 1106], [9539, 8323, 8969, 3611], [9670, 8323, 2172, 4883], [2172, 1589, 7567], [3798, 9672, 4255]]


In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [15]:
sent_length = 8
pre_pad = pad_sequences(one, padding='pre', maxlen=sent_length)


In [16]:
print(pre_pad)

[[   0    0    0 2172 1215 8323 2172 1106]
 [   0    0    0    0 9539 8323 8969 3611]
 [   0    0    0    0 9670 8323 2172 4883]
 [   0    0    0    0    0 2172 1589 7567]
 [   0    0    0    0    0 3798 9672 4255]]


In [17]:
post_pad = pad_sequences(one, padding='post', maxlen=sent_length)

In [18]:
print(post_pad)

[[2172 1215 8323 2172 1106    0    0    0]
 [9539 8323 8969 3611    0    0    0    0]
 [9670 8323 2172 4883    0    0    0    0]
 [2172 1589 7567    0    0    0    0    0]
 [3798 9672 4255    0    0    0    0    0]]


In [19]:
dim = 10

In [27]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Input

model = Sequential([
    Input(shape=(sent_length,)),
    Embedding(input_dim=voc_size, output_dim=10)
])

model.compile(optimizer='adam', loss='mse')

model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [30]:
model.predict(np.expand_dims(pre_pad[0], axis=0))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step


array([[[ 0.02728862,  0.03143046, -0.02689778, -0.03074633,
          0.00687168, -0.03049345, -0.02197137, -0.04398313,
          0.00273491,  0.03941628],
        [ 0.02728862,  0.03143046, -0.02689778, -0.03074633,
          0.00687168, -0.03049345, -0.02197137, -0.04398313,
          0.00273491,  0.03941628],
        [ 0.02728862,  0.03143046, -0.02689778, -0.03074633,
          0.00687168, -0.03049345, -0.02197137, -0.04398313,
          0.00273491,  0.03941628],
        [-0.03587695,  0.04232386, -0.01711348,  0.01221752,
         -0.01149319,  0.03068148, -0.00173544,  0.03648248,
         -0.02882471, -0.04267467],
        [-0.04620356, -0.03730528, -0.03142855, -0.01851748,
         -0.03649924,  0.01289214,  0.02958978,  0.04228835,
         -0.02526878,  0.01791408],
        [ 0.02281685,  0.03700877, -0.02742233,  0.04844749,
          0.0421649 , -0.01706128, -0.01589824,  0.02457464,
          0.001385  ,  0.04603354],
        [-0.03587695,  0.04232386, -0.01711348,  0.0

In [33]:
print(model.predict(pre_pad))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 291ms/step
[[[ 0.02728862  0.03143046 -0.02689778 -0.03074633  0.00687168
   -0.03049345 -0.02197137 -0.04398313  0.00273491  0.03941628]
  [ 0.02728862  0.03143046 -0.02689778 -0.03074633  0.00687168
   -0.03049345 -0.02197137 -0.04398313  0.00273491  0.03941628]
  [ 0.02728862  0.03143046 -0.02689778 -0.03074633  0.00687168
   -0.03049345 -0.02197137 -0.04398313  0.00273491  0.03941628]
  [-0.03587695  0.04232386 -0.01711348  0.01221752 -0.01149319
    0.03068148 -0.00173544  0.03648248 -0.02882471 -0.04267467]
  [-0.04620356 -0.03730528 -0.03142855 -0.01851748 -0.03649924
    0.01289214  0.02958978  0.04228835 -0.02526878  0.01791408]
  [ 0.02281685  0.03700877 -0.02742233  0.04844749  0.0421649
   -0.01706128 -0.01589824  0.02457464  0.001385    0.04603354]
  [-0.03587695  0.04232386 -0.01711348  0.01221752 -0.01149319
    0.03068148 -0.00173544  0.03648248 -0.02882471 -0.04267467]
  [ 0.04084165 -0.04117423 -0.01942864 -0.02167037  0.02258536
    0.0427