In [ ]:
! pip install tensorflow

In [4]:
import tensorflow as tf

In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
sent = [
    'the ball of the century',
    'greatest of all time',
    'head of the table',
    'the peoples champ',
    'rest in peace'
]

In [7]:
sent

['the ball of the century',
 'greatest of all time',
 'head of the table',
 'the peoples champ',
 'rest in peace']

In [8]:
voc_size = 10000

In [9]:
one = [one_hot(words, voc_size) for words in sent]
print(one)

[[2172, 1215, 8323, 2172, 1106], [9539, 8323, 8969, 3611], [9670, 8323, 2172, 4883], [2172, 1589, 7567], [3798, 9672, 4255]]


In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [15]:
sent_length = 8
pre_pad = pad_sequences(one, padding='pre', maxlen=sent_length)


In [16]:
print(pre_pad)

[[   0    0    0 2172 1215 8323 2172 1106]
 [   0    0    0    0 9539 8323 8969 3611]
 [   0    0    0    0 9670 8323 2172 4883]
 [   0    0    0    0    0 2172 1589 7567]
 [   0    0    0    0    0 3798 9672 4255]]


In [17]:
post_pad = pad_sequences(one, padding='post', maxlen=sent_length)

In [18]:
print(post_pad)

[[2172 1215 8323 2172 1106    0    0    0]
 [9539 8323 8969 3611    0    0    0    0]
 [9670 8323 2172 4883    0    0    0    0]
 [2172 1589 7567    0    0    0    0    0]
 [3798 9672 4255    0    0    0    0    0]]
